SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `tan`.`comments` CHANGE COLUMN `deleted` `deleted` VARCHAR(1) NOT NULL DEFAULT 0  ;

ALTER TABLE `tan`.`object` CHANGE COLUMN `NSFW` `nsfw` VARCHAR(1) NOT NULL DEFAULT 0  , CHANGE COLUMN `deleted` `deleted` VARCHAR(1) NOT NULL DEFAULT 0  ;

ALTER TABLE `tan`.`user` CHANGE COLUMN `confirmed` `confirmed` VARCHAR(1) NOT NULL DEFAULT 0  , CHANGE COLUMN `deleted` `deleted` VARCHAR(1) NOT NULL DEFAULT 0  ;

ALTER TABLE `tan`.`cms` CHANGE COLUMN `deleted` `deleted` VARCHAR(1) NOT NULL DEFAULT 0  , CHANGE COLUMN `system` `system` VARCHAR(1) NOT NULL DEFAULT 0  , CHANGE COLUMN `nowrapper` `nowrapper` VARCHAR(1) NOT NULL DEFAULT 0  ;

ALTER TABLE `tan`.`lotto` CHANGE COLUMN `confirmed` `confirmed` VARCHAR(1) NOT NULL DEFAULT 0  , CHANGE COLUMN `winner` `winner` VARCHAR(1) NOT NULL DEFAULT 0  ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
