ALTER TABLE `tan`.`blog` CHANGE COLUMN `blog_id` `blog_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `picture_id` `picture_id` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`comments` CHANGE COLUMN `comment_id` `comment_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `user_id` `user_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `object_id` `object_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `number` `number` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`link` CHANGE COLUMN `link_id` `link_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `picture_id` `picture_id` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`object` CHANGE COLUMN `object_id` `object_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `user_id` `user_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `views` `views` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0  , CHANGE COLUMN `plus` `plus` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0  , CHANGE COLUMN `minus` `minus` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0  , CHANGE COLUMN `comments` `comments` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0  , CHANGE COLUMN `score` `score` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `tan`.`picture` CHANGE COLUMN `picture_id` `picture_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `x` `x` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `y` `y` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `size` `size` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`plus_minus` CHANGE COLUMN `plus_minus_id` `plus_minus_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `object_id` `object_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `user_id` `user_id` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`poll` CHANGE COLUMN `poll_id` `poll_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `picture_id` `picture_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `votes` `votes` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `tan`.`poll_answer` CHANGE COLUMN `answer_id` `answer_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `poll_id` `poll_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `votes` `votes` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `tan`.`poll_vote` CHANGE COLUMN `vote_id` `vote_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `answer_id` `answer_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `user_id` `user_id` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`profile` CHANGE COLUMN `profile_id` `profile_id` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`tag_objects` DROP COLUMN `user_id` , CHANGE COLUMN `object_tag_id` `object_tag_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `tag_id` `tag_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `object_id` `object_id` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`tags` CHANGE COLUMN `tag_id` `tag_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  ;

ALTER TABLE `tan`.`user` CHANGE COLUMN `user_id` `user_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `tcs` `tcs` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL  ;

ALTER TABLE `tan`.`user_tokens` CHANGE COLUMN `token_id` `token_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `user_id` `user_id` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`views` CHANGE COLUMN `view_id` `view_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `object_id` `object_id` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL  , CHANGE COLUMN `user_id` `user_id` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `tan`.`user_admin` CHANGE COLUMN `user_id` `user_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `admin_id` `admin_id` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`admin` CHANGE COLUMN `admin_id` `admin_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  ;

ALTER TABLE `tan`.`admin_log` CHANGE COLUMN `log_id` `log_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `admin_id` `admin_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `user_id` `user_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `comment_id` `comment_id` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL  , CHANGE COLUMN `object_id` `object_id` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `tan`.`video` CHANGE COLUMN `video_id` `video_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `picture_id` `picture_id` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`forum` CHANGE COLUMN `forum_id` `forum_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `picture_id` `picture_id` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`cms` CHANGE COLUMN `cms_id` `cms_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `user_id` `user_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `revision` `revision` MEDIUMINT(8) UNSIGNED NOT NULL;

ALTER TABLE `tan`.`lotto` CHANGE COLUMN `lotto_id` `lotto_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT  , CHANGE COLUMN `user_id` `user_id` MEDIUMINT(8) UNSIGNED NOT NULL  , CHANGE COLUMN `number` `number` TINYINT(3) UNSIGNED NOT NULL;
